# Generated by Django 2.2.1 on 2021-08-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iekari', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentRoom',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='物件ID')),
                ('pref_name', models.CharField(max_length=20, verbose_name='都道府県')),
                ('city_name', models.CharField(max_length=50, verbose_name='市区町村')),
                ('district_name', models.CharField(max_length=50, verbose_name='町丁目')),
                ('built_year', models.IntegerField(verbose_name='築年')),
                ('structure', models.CharField(max_length=20, verbose_name='構造')),
                ('top_floor_num', models.IntegerField(verbose_name='最上階数')),
                ('room_type', models.CharField(max_length=20, verbose_name='間取り')),
                ('price', models.FloatField(verbose_name='平米単価')),
                ('area', models.FloatField(verbose_name='専有面積')),
                ('latitude', models.FloatField(verbose_name='物件緯度')),
                ('longitude', models.FloatField(verbose_name='物件経度')),
                ('nearest_station', models.CharField(max_length=50, verbose_name='最寄り駅')),
                ('dist_to_nearest_station', models.FloatField(verbose_name='最寄駅までの距離')),
            ],
            options={
                'verbose_name': '賃貸物件データ',
                'verbose_name_plural': '賃貸物件データ',
            },
        ),
    ]
